export const features = [
  [
    "1 Click E-Way Bill",
    "Android & iOS App",
    "Purchase Order",
    "Job Work",
    "Payment Receipt",
    "Staff Account",
    "Customized Report",
    "Expenses Tracking",
    "Import / Export Data",
    "Payment Reminder",
  ],
  [
    "1 Click E-Invoice",
    "Professional GST Invoices",
    "Proforma & Quotation",
    "Sale Order",
    "Credit / Debit Note",
    "Convert & Duplicate",
    "Share on Email, WhatsApp",
    "GST Return Report",
    "11+ Invoice Template",
    "Cheque Printing",
  ],
  [
    "1 Click Add Customer",
    "Delivery Challan",
    "Export / SEZ Invoices",
    "Multi Currency Invoice",
    "Inventory Management",
    "Barcode Scanning",
    "Shipping Label",
    "A4, A5 & Thermal Print",
    "Tally Integration",
    "Phone & Email Support",
  ],
];
