export const free = {
  id: 1,
  features: [
    "No ads, No branding",
    "Sales & Purchase Invoice",
    "Customer & Product Management",
    "Inventory Management",
    "Payment Receipt",
    "Mobile App Access",
    "Phone & Email Support",
    "Share invoices on WhatsApp",
    "Max 25 items per document",
    "Max 3000 documents per year",
  ],
};
export const paid = {
  id: 2,
  features: [
    "No ads, No branding",
    "Unlimited Sales & Purchase Invoice",
    "Customer & Product Management",
    "Advanced Inventory Management",
    "Payment Receipt & Expense Tracking",
    "Multi-user Access with Roles",
    "Integration with Bank Accounts",
    "GST & Tax Calculation",
    "E-way Bill & E-invoice Generation",
    "Detailed Business Reports & Analytics",
    "Mobile & Desktop App Access",
    "Priority Phone & Email Support",
    "24/7 Live Chat Support",
    "Share invoices on WhatsApp & Email",
    "Max Unlimited items per document",
    "Max Unlimited documents per year",
    "Data Import & Export (Excel/CSV)",
    "Invoice Customization with Branding",
    "Recurring Invoices & Auto-reminders",
    "Multi-Currency Support",
    "Bulk Product Uploads",
    "Expense & Profit-Loss Reports",
    "Access Control & User Permissions",
    "API Access for Developers",
    "Offline Mode for Invoicing",
    "Cloud Backup & Data Security",
    "Automated Payment Reminders",
    "Vendor & Supplier Management",
    "Discount & Coupon Management",
    "POS (Point of Sale) System Integration",
  ],
};
